project_id = "lmjjghvrjgffmbidajih"

[functions.api-data]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = true

[functions.generate-news-summary]
verify_jwt = true

[functions.generate-plain-language]
verify_jwt = true

[functions.get-umami-analytics]
verify_jwt = false

[functions.get-umami-config]
verify_jwt = false

[functions.manage-user-password]
verify_jwt = true

[functions.send-status-alert]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = true

[functions.send-invite]
verify_jwt = true

[functions.test-email]
verify_jwt = true

[functions.update-own-password]
verify_jwt = true

[functions.send-unsubscribe-confirmation]
verify_jwt = false
